# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.8", "3.9", "3.10", "3.11", "3.12"]
        tox_env: [""]
        include:
          - python: "3.11"
            tox_env: "-e min_versions"
          - python: "3.11"
            tox_env: "-e max_versions"

    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}

    - name: Install tox
      run: python -m pip install --upgrade pip tox

    - name: Run tox
      # The TOXENV environment variable is used by tox to select which
      # environments to run. We link the Python version from the matrix
      # to the corresponding tox environment (e.g., py38, py39).
      # We also run the 'lint' environment in a separate job.
      run: tox ${{ matrix.tox_env }} -e py${{ matrix.python }}

  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.11' # Use a recent Python version for linting

    - name: Install tox
      run: python -m pip install --upgrade pip tox

    - name: Run linting and security checks
      run: tox -e lint